# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Asignatura(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, nombre_asignatura: str=None, codigo: int=None, profesor: int=None, num_departamento: int=None):
        """
        Asignatura - a model defined in Swagger

        :param nombre_asignatura: The nombre_asignatura of this Asignatura.
        :type nombre_asignatura: str
        :param codigo: The codigo of this Asignatura.
        :type codigo: int
        :param profesor: The profesor of this Asignatura.
        :type profesor: int
        :param num_departamento: The num_departamento of this Asignatura.
        :type num_departamento: int
        """
        self.swagger_types = {
            'nombre_asignatura': str,
            'codigo': int,
            'profesor': int,
            'num_departamento': int
        }

        self.attribute_map = {
            'nombre_asignatura': 'Nombre_Asignatura',
            'codigo': 'Codigo',
            'profesor': 'Profesor',
            'num_departamento': 'Num_Departamento'
        }

        self._nombre_asignatura = nombre_asignatura
        self._codigo = codigo
        self._profesor = profesor
        self._num_departamento = num_departamento

    @classmethod
    def from_dict(cls, dikt) -> 'Asignatura':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The asignatura of this Asignatura.
        :rtype: Asignatura
        """
        return deserialize_model(dikt, cls)

    @property
    def nombre_asignatura(self) -> str:
        """
        Gets the nombre_asignatura of this Asignatura.

        :return: The nombre_asignatura of this Asignatura.
        :rtype: str
        """
        return self._nombre_asignatura

    @nombre_asignatura.setter
    def nombre_asignatura(self, nombre_asignatura: str):
        """
        Sets the nombre_asignatura of this Asignatura.

        :param nombre_asignatura: The nombre_asignatura of this Asignatura.
        :type nombre_asignatura: str
        """

        self._nombre_asignatura = nombre_asignatura

    @property
    def codigo(self) -> int:
        """
        Gets the codigo of this Asignatura.

        :return: The codigo of this Asignatura.
        :rtype: int
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: int):
        """
        Sets the codigo of this Asignatura.

        :param codigo: The codigo of this Asignatura.
        :type codigo: int
        """

        self._codigo = codigo

    @property
    def profesor(self) -> int:
        """
        Gets the profesor of this Asignatura.

        :return: The profesor of this Asignatura.
        :rtype: int
        """
        return self._profesor

    @profesor.setter
    def profesor(self, profesor: int):
        """
        Sets the profesor of this Asignatura.

        :param profesor: The profesor of this Asignatura.
        :type profesor: int
        """

        self._profesor = profesor

    @property
    def num_departamento(self) -> int:
        """
        Gets the num_departamento of this Asignatura.

        :return: The num_departamento of this Asignatura.
        :rtype: int
        """
        return self._num_departamento

    @num_departamento.setter
    def num_departamento(self, num_departamento: int):
        """
        Sets the num_departamento of this Asignatura.

        :param num_departamento: The num_departamento of this Asignatura.
        :type num_departamento: int
        """

        self._num_departamento = num_departamento

