# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Profesor(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni_profesor: int=None, carga_trabajo: int=None):
        """
        Profesor - a model defined in Swagger

        :param dni_profesor: The dni_profesor of this Profesor.
        :type dni_profesor: int
        :param carga_trabajo: The carga_trabajo of this Profesor.
        :type carga_trabajo: int
        """
        self.swagger_types = {
            'dni_profesor': int,
            'carga_trabajo': int
        }

        self.attribute_map = {
            'dni_profesor': 'DNI_profesor',
            'carga_trabajo': 'Carga_Trabajo'
        }

        self._dni_profesor = dni_profesor
        self._carga_trabajo = carga_trabajo

    @classmethod
    def from_dict(cls, dikt) -> 'Profesor':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The profesor of this Profesor.
        :rtype: Profesor
        """
        return deserialize_model(dikt, cls)

    @property
    def dni_profesor(self) -> int:
        """
        Gets the dni_profesor of this Profesor.

        :return: The dni_profesor of this Profesor.
        :rtype: int
        """
        return self._dni_profesor

    @dni_profesor.setter
    def dni_profesor(self, dni_profesor: int):
        """
        Sets the dni_profesor of this Profesor.

        :param dni_profesor: The dni_profesor of this Profesor.
        :type dni_profesor: int
        """

        self._dni_profesor = dni_profesor

    @property
    def carga_trabajo(self) -> int:
        """
        Gets the carga_trabajo of this Profesor.

        :return: The carga_trabajo of this Profesor.
        :rtype: int
        """
        return self._carga_trabajo

    @carga_trabajo.setter
    def carga_trabajo(self, carga_trabajo: int):
        """
        Sets the carga_trabajo of this Profesor.

        :param carga_trabajo: The carga_trabajo of this Profesor.
        :type carga_trabajo: int
        """

        self._carga_trabajo = carga_trabajo

