# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Dni2(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni: int=None, id: int=None, precio: int=None, plazos: int=None, reserva: int=None):
        """
        Dni2 - a model defined in Swagger

        :param dni: The dni of this Dni2.
        :type dni: int
        :param id: The id of this Dni2.
        :type id: int
        :param precio: The precio of this Dni2.
        :type precio: int
        :param plazos: The plazos of this Dni2.
        :type plazos: int
        :param reserva: The reserva of this Dni2.
        :type reserva: int
        """
        self.swagger_types = {
            'dni': int,
            'id': int,
            'precio': int,
            'plazos': int,
            'reserva': int
        }

        self.attribute_map = {
            'dni': 'dni',
            'id': 'id',
            'precio': 'precio',
            'plazos': 'plazos',
            'reserva': 'reserva'
        }

        self._dni = dni
        self._id = id
        self._precio = precio
        self._plazos = plazos
        self._reserva = reserva

    @classmethod
    def from_dict(cls, dikt) -> 'Dni2':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dni_2 of this Dni2.
        :rtype: Dni2
        """
        return deserialize_model(dikt, cls)

    @property
    def dni(self) -> int:
        """
        Gets the dni of this Dni2.

        :return: The dni of this Dni2.
        :rtype: int
        """
        return self._dni

    @dni.setter
    def dni(self, dni: int):
        """
        Sets the dni of this Dni2.

        :param dni: The dni of this Dni2.
        :type dni: int
        """
        if dni is None:
            raise ValueError("Invalid value for `dni`, must not be `None`")

        self._dni = dni

    @property
    def id(self) -> int:
        """
        Gets the id of this Dni2.

        :return: The id of this Dni2.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Dni2.

        :param id: The id of this Dni2.
        :type id: int
        """

        self._id = id

    @property
    def precio(self) -> int:
        """
        Gets the precio of this Dni2.

        :return: The precio of this Dni2.
        :rtype: int
        """
        return self._precio

    @precio.setter
    def precio(self, precio: int):
        """
        Sets the precio of this Dni2.

        :param precio: The precio of this Dni2.
        :type precio: int
        """

        self._precio = precio

    @property
    def plazos(self) -> int:
        """
        Gets the plazos of this Dni2.

        :return: The plazos of this Dni2.
        :rtype: int
        """
        return self._plazos

    @plazos.setter
    def plazos(self, plazos: int):
        """
        Sets the plazos of this Dni2.

        :param plazos: The plazos of this Dni2.
        :type plazos: int
        """

        self._plazos = plazos

    @property
    def reserva(self) -> int:
        """
        Gets the reserva of this Dni2.

        :return: The reserva of this Dni2.
        :rtype: int
        """
        return self._reserva

    @reserva.setter
    def reserva(self, reserva: int):
        """
        Sets the reserva of this Dni2.

        :param reserva: The reserva of this Dni2.
        :type reserva: int
        """

        self._reserva = reserva

