# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ActualizacionMatricula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni_alumno: int=None, precio: int=None):
        """
        ActualizacionMatricula - a model defined in Swagger

        :param dni_alumno: The dni_alumno of this ActualizacionMatricula.
        :type dni_alumno: int
        :param precio: The precio of this ActualizacionMatricula.
        :type precio: int
        """
        self.swagger_types = {
            'dni_alumno': int,
            'precio': int
        }

        self.attribute_map = {
            'dni_alumno': 'dni_alumno',
            'precio': 'precio'
        }

        self._dni_alumno = dni_alumno
        self._precio = precio

    @classmethod
    def from_dict(cls, dikt) -> 'ActualizacionMatricula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The actualizacion_matricula of this ActualizacionMatricula.
        :rtype: ActualizacionMatricula
        """
        return deserialize_model(dikt, cls)

    @property
    def dni_alumno(self) -> int:
        """
        Gets the dni_alumno of this ActualizacionMatricula.

        :return: The dni_alumno of this ActualizacionMatricula.
        :rtype: int
        """
        return self._dni_alumno

    @dni_alumno.setter
    def dni_alumno(self, dni_alumno: int):
        """
        Sets the dni_alumno of this ActualizacionMatricula.

        :param dni_alumno: The dni_alumno of this ActualizacionMatricula.
        :type dni_alumno: int
        """

        self._dni_alumno = dni_alumno

    @property
    def precio(self) -> int:
        """
        Gets the precio of this ActualizacionMatricula.

        :return: The precio of this ActualizacionMatricula.
        :rtype: int
        """
        return self._precio

    @precio.setter
    def precio(self, precio: int):
        """
        Sets the precio of this ActualizacionMatricula.

        :param precio: The precio of this ActualizacionMatricula.
        :type precio: int
        """

        self._precio = precio

