# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ActualizacionPago(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni_profesor: int=None, nomina: int=None):
        """
        ActualizacionPago - a model defined in Swagger

        :param dni_profesor: The dni_profesor of this ActualizacionPago.
        :type dni_profesor: int
        :param nomina: The nomina of this ActualizacionPago.
        :type nomina: int
        """
        self.swagger_types = {
            'dni_profesor': int,
            'nomina': int
        }

        self.attribute_map = {
            'dni_profesor': 'dni_profesor',
            'nomina': 'nomina'
        }

        self._dni_profesor = dni_profesor
        self._nomina = nomina

    @classmethod
    def from_dict(cls, dikt) -> 'ActualizacionPago':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The actualizacion_pago of this ActualizacionPago.
        :rtype: ActualizacionPago
        """
        return deserialize_model(dikt, cls)

    @property
    def dni_profesor(self) -> int:
        """
        Gets the dni_profesor of this ActualizacionPago.

        :return: The dni_profesor of this ActualizacionPago.
        :rtype: int
        """
        return self._dni_profesor

    @dni_profesor.setter
    def dni_profesor(self, dni_profesor: int):
        """
        Sets the dni_profesor of this ActualizacionPago.

        :param dni_profesor: The dni_profesor of this ActualizacionPago.
        :type dni_profesor: int
        """

        self._dni_profesor = dni_profesor

    @property
    def nomina(self) -> int:
        """
        Gets the nomina of this ActualizacionPago.

        :return: The nomina of this ActualizacionPago.
        :rtype: int
        """
        return self._nomina

    @nomina.setter
    def nomina(self, nomina: int):
        """
        Sets the nomina of this ActualizacionPago.

        :param nomina: The nomina of this ActualizacionPago.
        :type nomina: int
        """

        self._nomina = nomina

