# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Matricula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni_alumno: int=None, id: int=None, precio: int=None, plazos: int=None, reserva: int=None):
        """
        Matricula - a model defined in Swagger

        :param dni_alumno: The dni_alumno of this Matricula.
        :type dni_alumno: int
        :param id: The id of this Matricula.
        :type id: int
        :param precio: The precio of this Matricula.
        :type precio: int
        :param plazos: The plazos of this Matricula.
        :type plazos: int
        :param reserva: The reserva of this Matricula.
        :type reserva: int
        """
        self.swagger_types = {
            'dni_alumno': int,
            'id': int,
            'precio': int,
            'plazos': int,
            'reserva': int
        }

        self.attribute_map = {
            'dni_alumno': 'dni_alumno',
            'id': 'id',
            'precio': 'precio',
            'plazos': 'plazos',
            'reserva': 'reserva'
        }

        self._dni_alumno = dni_alumno
        self._id = id
        self._precio = precio
        self._plazos = plazos
        self._reserva = reserva

    @classmethod
    def from_dict(cls, dikt) -> 'Matricula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The matricula of this Matricula.
        :rtype: Matricula
        """
        return deserialize_model(dikt, cls)

    @property
    def dni_alumno(self) -> int:
        """
        Gets the dni_alumno of this Matricula.

        :return: The dni_alumno of this Matricula.
        :rtype: int
        """
        return self._dni_alumno

    @dni_alumno.setter
    def dni_alumno(self, dni_alumno: int):
        """
        Sets the dni_alumno of this Matricula.

        :param dni_alumno: The dni_alumno of this Matricula.
        :type dni_alumno: int
        """

        self._dni_alumno = dni_alumno

    @property
    def id(self) -> int:
        """
        Gets the id of this Matricula.

        :return: The id of this Matricula.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Matricula.

        :param id: The id of this Matricula.
        :type id: int
        """

        self._id = id

    @property
    def precio(self) -> int:
        """
        Gets the precio of this Matricula.

        :return: The precio of this Matricula.
        :rtype: int
        """
        return self._precio

    @precio.setter
    def precio(self, precio: int):
        """
        Sets the precio of this Matricula.

        :param precio: The precio of this Matricula.
        :type precio: int
        """

        self._precio = precio

    @property
    def plazos(self) -> int:
        """
        Gets the plazos of this Matricula.

        :return: The plazos of this Matricula.
        :rtype: int
        """
        return self._plazos

    @plazos.setter
    def plazos(self, plazos: int):
        """
        Sets the plazos of this Matricula.

        :param plazos: The plazos of this Matricula.
        :type plazos: int
        """

        self._plazos = plazos

    @property
    def reserva(self) -> int:
        """
        Gets the reserva of this Matricula.

        :return: The reserva of this Matricula.
        :rtype: int
        """
        return self._reserva

    @reserva.setter
    def reserva(self, reserva: int):
        """
        Sets the reserva of this Matricula.

        :param reserva: The reserva of this Matricula.
        :type reserva: int
        """

        self._reserva = reserva

