# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Departamento(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, edificio: str=None, nomb_departamento: str=None, num_departamento: int=None, titulacion: str=None):
        """
        Departamento - a model defined in Swagger

        :param edificio: The edificio of this Departamento.
        :type edificio: str
        :param nomb_departamento: The nomb_departamento of this Departamento.
        :type nomb_departamento: str
        :param num_departamento: The num_departamento of this Departamento.
        :type num_departamento: int
        :param titulacion: The titulacion of this Departamento.
        :type titulacion: str
        """
        self.swagger_types = {
            'edificio': str,
            'nomb_departamento': str,
            'num_departamento': int,
            'titulacion': str
        }

        self.attribute_map = {
            'edificio': 'Edificio',
            'nomb_departamento': 'Nomb_Departamento',
            'num_departamento': 'Num_Departamento',
            'titulacion': 'Titulacion'
        }

        self._edificio = edificio
        self._nomb_departamento = nomb_departamento
        self._num_departamento = num_departamento
        self._titulacion = titulacion

    @classmethod
    def from_dict(cls, dikt) -> 'Departamento':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The departamento of this Departamento.
        :rtype: Departamento
        """
        return deserialize_model(dikt, cls)

    @property
    def edificio(self) -> str:
        """
        Gets the edificio of this Departamento.

        :return: The edificio of this Departamento.
        :rtype: str
        """
        return self._edificio

    @edificio.setter
    def edificio(self, edificio: str):
        """
        Sets the edificio of this Departamento.

        :param edificio: The edificio of this Departamento.
        :type edificio: str
        """

        self._edificio = edificio

    @property
    def nomb_departamento(self) -> str:
        """
        Gets the nomb_departamento of this Departamento.

        :return: The nomb_departamento of this Departamento.
        :rtype: str
        """
        return self._nomb_departamento

    @nomb_departamento.setter
    def nomb_departamento(self, nomb_departamento: str):
        """
        Sets the nomb_departamento of this Departamento.

        :param nomb_departamento: The nomb_departamento of this Departamento.
        :type nomb_departamento: str
        """

        self._nomb_departamento = nomb_departamento

    @property
    def num_departamento(self) -> int:
        """
        Gets the num_departamento of this Departamento.

        :return: The num_departamento of this Departamento.
        :rtype: int
        """
        return self._num_departamento

    @num_departamento.setter
    def num_departamento(self, num_departamento: int):
        """
        Sets the num_departamento of this Departamento.

        :param num_departamento: The num_departamento of this Departamento.
        :type num_departamento: int
        """

        self._num_departamento = num_departamento

    @property
    def titulacion(self) -> str:
        """
        Gets the titulacion of this Departamento.

        :return: The titulacion of this Departamento.
        :rtype: str
        """
        return self._titulacion

    @titulacion.setter
    def titulacion(self, titulacion: str):
        """
        Sets the titulacion of this Departamento.

        :param titulacion: The titulacion of this Departamento.
        :type titulacion: str
        """

        self._titulacion = titulacion

