# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Cambio(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, codigo: int=None, profesor: int=None):
        """
        Cambio - a model defined in Swagger

        :param codigo: The codigo of this Cambio.
        :type codigo: int
        :param profesor: The profesor of this Cambio.
        :type profesor: int
        """
        self.swagger_types = {
            'codigo': int,
            'profesor': int
        }

        self.attribute_map = {
            'codigo': 'Codigo',
            'profesor': 'Profesor'
        }

        self._codigo = codigo
        self._profesor = profesor

    @classmethod
    def from_dict(cls, dikt) -> 'Cambio':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cambio of this Cambio.
        :rtype: Cambio
        """
        return deserialize_model(dikt, cls)

    @property
    def codigo(self) -> int:
        """
        Gets the codigo of this Cambio.

        :return: The codigo of this Cambio.
        :rtype: int
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: int):
        """
        Sets the codigo of this Cambio.

        :param codigo: The codigo of this Cambio.
        :type codigo: int
        """

        self._codigo = codigo

    @property
    def profesor(self) -> int:
        """
        Gets the profesor of this Cambio.

        :return: The profesor of this Cambio.
        :rtype: int
        """
        return self._profesor

    @profesor.setter
    def profesor(self, profesor: int):
        """
        Sets the profesor of this Cambio.

        :param profesor: The profesor of this Cambio.
        :type profesor: int
        """

        self._profesor = profesor

