# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class CambioDeparta(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, codigo: int=None, num_departamento: int=None):
        """
        CambioDeparta - a model defined in Swagger

        :param codigo: The codigo of this CambioDeparta.
        :type codigo: int
        :param num_departamento: The num_departamento of this CambioDeparta.
        :type num_departamento: int
        """
        self.swagger_types = {
            'codigo': int,
            'num_departamento': int
        }

        self.attribute_map = {
            'codigo': 'Codigo',
            'num_departamento': 'Num_Departamento'
        }

        self._codigo = codigo
        self._num_departamento = num_departamento

    @classmethod
    def from_dict(cls, dikt) -> 'CambioDeparta':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cambioDeparta of this CambioDeparta.
        :rtype: CambioDeparta
        """
        return deserialize_model(dikt, cls)

    @property
    def codigo(self) -> int:
        """
        Gets the codigo of this CambioDeparta.

        :return: The codigo of this CambioDeparta.
        :rtype: int
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: int):
        """
        Sets the codigo of this CambioDeparta.

        :param codigo: The codigo of this CambioDeparta.
        :type codigo: int
        """

        self._codigo = codigo

    @property
    def num_departamento(self) -> int:
        """
        Gets the num_departamento of this CambioDeparta.

        :return: The num_departamento of this CambioDeparta.
        :rtype: int
        """
        return self._num_departamento

    @num_departamento.setter
    def num_departamento(self, num_departamento: int):
        """
        Sets the num_departamento of this CambioDeparta.

        :param num_departamento: The num_departamento of this CambioDeparta.
        :type num_departamento: int
        """

        self._num_departamento = num_departamento

