# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Matricula1(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, aprobada: int=None, coste: int=None, dni_alumno: int=None, id_asignatura: int=None):
        """
        Matricula1 - a model defined in Swagger

        :param aprobada: The aprobada of this Matricula1.
        :type aprobada: int
        :param coste: The coste of this Matricula1.
        :type coste: int
        :param dni_alumno: The dni_alumno of this Matricula1.
        :type dni_alumno: int
        :param id_asignatura: The id_asignatura of this Matricula1.
        :type id_asignatura: int
        """
        self.swagger_types = {
            'aprobada': int,
            'coste': int,
            'dni_alumno': int,
            'id_asignatura': int
        }

        self.attribute_map = {
            'aprobada': 'aprobada',
            'coste': 'coste',
            'dni_alumno': 'DNI_alumno',
            'id_asignatura': 'id_asignatura'
        }

        self._aprobada = aprobada
        self._coste = coste
        self._dni_alumno = dni_alumno
        self._id_asignatura = id_asignatura

    @classmethod
    def from_dict(cls, dikt) -> 'Matricula1':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The matricula_1 of this Matricula1.
        :rtype: Matricula1
        """
        return deserialize_model(dikt, cls)

    @property
    def aprobada(self) -> int:
        """
        Gets the aprobada of this Matricula1.

        :return: The aprobada of this Matricula1.
        :rtype: int
        """
        return self._aprobada

    @aprobada.setter
    def aprobada(self, aprobada: int):
        """
        Sets the aprobada of this Matricula1.

        :param aprobada: The aprobada of this Matricula1.
        :type aprobada: int
        """

        self._aprobada = aprobada

    @property
    def coste(self) -> int:
        """
        Gets the coste of this Matricula1.

        :return: The coste of this Matricula1.
        :rtype: int
        """
        return self._coste

    @coste.setter
    def coste(self, coste: int):
        """
        Sets the coste of this Matricula1.

        :param coste: The coste of this Matricula1.
        :type coste: int
        """

        self._coste = coste

    @property
    def dni_alumno(self) -> int:
        """
        Gets the dni_alumno of this Matricula1.

        :return: The dni_alumno of this Matricula1.
        :rtype: int
        """
        return self._dni_alumno

    @dni_alumno.setter
    def dni_alumno(self, dni_alumno: int):
        """
        Sets the dni_alumno of this Matricula1.

        :param dni_alumno: The dni_alumno of this Matricula1.
        :type dni_alumno: int
        """

        self._dni_alumno = dni_alumno

    @property
    def id_asignatura(self) -> int:
        """
        Gets the id_asignatura of this Matricula1.

        :return: The id_asignatura of this Matricula1.
        :rtype: int
        """
        return self._id_asignatura

    @id_asignatura.setter
    def id_asignatura(self, id_asignatura: int):
        """
        Sets the id_asignatura of this Matricula1.

        :param id_asignatura: The id_asignatura of this Matricula1.
        :type id_asignatura: int
        """

        self._id_asignatura = id_asignatura

