# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Asignatura(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, codigo_asignatura: int=None, numero_alumnos: int=None):
        """
        Asignatura - a model defined in Swagger

        :param codigo_asignatura: The codigo_asignatura of this Asignatura.
        :type codigo_asignatura: int
        :param numero_alumnos: The numero_alumnos of this Asignatura.
        :type numero_alumnos: int
        """
        self.swagger_types = {
            'codigo_asignatura': int,
            'numero_alumnos': int
        }

        self.attribute_map = {
            'codigo_asignatura': 'codigo_asignatura',
            'numero_alumnos': 'numero_alumnos'
        }

        self._codigo_asignatura = codigo_asignatura
        self._numero_alumnos = numero_alumnos

    @classmethod
    def from_dict(cls, dikt) -> 'Asignatura':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asignatura of this Asignatura.
        :rtype: Asignatura
        """
        return deserialize_model(dikt, cls)

    @property
    def codigo_asignatura(self) -> int:
        """
        Gets the codigo_asignatura of this Asignatura.

        :return: The codigo_asignatura of this Asignatura.
        :rtype: int
        """
        return self._codigo_asignatura

    @codigo_asignatura.setter
    def codigo_asignatura(self, codigo_asignatura: int):
        """
        Sets the codigo_asignatura of this Asignatura.

        :param codigo_asignatura: The codigo_asignatura of this Asignatura.
        :type codigo_asignatura: int
        """

        self._codigo_asignatura = codigo_asignatura

    @property
    def numero_alumnos(self) -> int:
        """
        Gets the numero_alumnos of this Asignatura.

        :return: The numero_alumnos of this Asignatura.
        :rtype: int
        """
        return self._numero_alumnos

    @numero_alumnos.setter
    def numero_alumnos(self, numero_alumnos: int):
        """
        Sets the numero_alumnos of this Asignatura.

        :param numero_alumnos: The numero_alumnos of this Asignatura.
        :type numero_alumnos: int
        """

        self._numero_alumnos = numero_alumnos

