# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Aula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, numero_aula: int=None, capacidad: int=None, precio: int=None, ocupada: bool=None):
        """
        Aula - a model defined in Swagger

        :param numero_aula: The numero_aula of this Aula.
        :type numero_aula: int
        :param capacidad: The capacidad of this Aula.
        :type capacidad: int
        :param precio: The precio of this Aula.
        :type precio: int
        :param ocupada: The ocupada of this Aula.
        :type ocupada: bool
        """
        self.swagger_types = {
            'numero_aula': int,
            'capacidad': int,
            'precio': int,
            'ocupada': bool
        }

        self.attribute_map = {
            'numero_aula': 'numero_aula',
            'capacidad': 'capacidad',
            'precio': 'precio',
            'ocupada': 'ocupada'
        }

        self._numero_aula = numero_aula
        self._capacidad = capacidad
        self._precio = precio
        self._ocupada = ocupada

    @classmethod
    def from_dict(cls, dikt) -> 'Aula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Aula of this Aula.
        :rtype: Aula
        """
        return deserialize_model(dikt, cls)

    @property
    def numero_aula(self) -> int:
        """
        Gets the numero_aula of this Aula.

        :return: The numero_aula of this Aula.
        :rtype: int
        """
        return self._numero_aula

    @numero_aula.setter
    def numero_aula(self, numero_aula: int):
        """
        Sets the numero_aula of this Aula.

        :param numero_aula: The numero_aula of this Aula.
        :type numero_aula: int
        """

        self._numero_aula = numero_aula

    @property
    def capacidad(self) -> int:
        """
        Gets the capacidad of this Aula.

        :return: The capacidad of this Aula.
        :rtype: int
        """
        return self._capacidad

    @capacidad.setter
    def capacidad(self, capacidad: int):
        """
        Sets the capacidad of this Aula.

        :param capacidad: The capacidad of this Aula.
        :type capacidad: int
        """

        self._capacidad = capacidad

    @property
    def precio(self) -> int:
        """
        Gets the precio of this Aula.

        :return: The precio of this Aula.
        :rtype: int
        """
        return self._precio

    @precio.setter
    def precio(self, precio: int):
        """
        Sets the precio of this Aula.

        :param precio: The precio of this Aula.
        :type precio: int
        """

        self._precio = precio

    @property
    def ocupada(self) -> bool:
        """
        Gets the ocupada of this Aula.

        :return: The ocupada of this Aula.
        :rtype: bool
        """
        return self._ocupada

    @ocupada.setter
    def ocupada(self, ocupada: bool):
        """
        Sets the ocupada of this Aula.

        :param ocupada: The ocupada of this Aula.
        :type ocupada: bool
        """

        self._ocupada = ocupada

