# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Departamento(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, codigo: int=None):
        """
        Departamento - a model defined in Swagger

        :param codigo: The codigo of this Departamento.
        :type codigo: int
        """
        self.swagger_types = {
            'codigo': int
        }

        self.attribute_map = {
            'codigo': 'codigo'
        }

        self._codigo = codigo

    @classmethod
    def from_dict(cls, dikt) -> 'Departamento':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Departamento of this Departamento.
        :rtype: Departamento
        """
        return deserialize_model(dikt, cls)

    @property
    def codigo(self) -> int:
        """
        Gets the codigo of this Departamento.

        :return: The codigo of this Departamento.
        :rtype: int
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: int):
        """
        Sets the codigo of this Departamento.

        :param codigo: The codigo of this Departamento.
        :type codigo: int
        """

        self._codigo = codigo

