# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GestionEYM(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, factura: str=None, ocupada: bool=None):
        """
        GestionEYM - a model defined in Swagger

        :param id: The id of this GestionEYM.
        :type id: int
        :param factura: The factura of this GestionEYM.
        :type factura: str
        :param ocupada: The ocupada of this GestionEYM.
        :type ocupada: bool
        """
        self.swagger_types = {
            'id': int,
            'factura': str,
            'ocupada': bool
        }

        self.attribute_map = {
            'id': 'id',
            'factura': 'factura',
            'ocupada': 'ocupada'
        }

        self._id = id
        self._factura = factura
        self._ocupada = ocupada

    @classmethod
    def from_dict(cls, dikt) -> 'GestionEYM':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GestionEYM of this GestionEYM.
        :rtype: GestionEYM
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this GestionEYM.

        :return: The id of this GestionEYM.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this GestionEYM.

        :param id: The id of this GestionEYM.
        :type id: int
        """

        self._id = id

    @property
    def factura(self) -> str:
        """
        Gets the factura of this GestionEYM.

        :return: The factura of this GestionEYM.
        :rtype: str
        """
        return self._factura

    @factura.setter
    def factura(self, factura: str):
        """
        Sets the factura of this GestionEYM.

        :param factura: The factura of this GestionEYM.
        :type factura: str
        """

        self._factura = factura

    @property
    def ocupada(self) -> bool:
        """
        Gets the ocupada of this GestionEYM.

        :return: The ocupada of this GestionEYM.
        :rtype: bool
        """
        return self._ocupada

    @ocupada.setter
    def ocupada(self, ocupada: bool):
        """
        Sets the ocupada of this GestionEYM.

        :param ocupada: The ocupada of this GestionEYM.
        :type ocupada: bool
        """

        self._ocupada = ocupada

