# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Reserva(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, numero_aula: int=None, horas: int=None):
        """
        Reserva - a model defined in Swagger

        :param numero_aula: The numero_aula of this Reserva.
        :type numero_aula: int
        :param horas: The horas of this Reserva.
        :type horas: int
        """
        self.swagger_types = {
            'numero_aula': int,
            'horas': int
        }

        self.attribute_map = {
            'numero_aula': 'numero_aula',
            'horas': 'horas'
        }

        self._numero_aula = numero_aula
        self._horas = horas

    @classmethod
    def from_dict(cls, dikt) -> 'Reserva':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reserva of this Reserva.
        :rtype: Reserva
        """
        return deserialize_model(dikt, cls)

    @property
    def numero_aula(self) -> int:
        """
        Gets the numero_aula of this Reserva.

        :return: The numero_aula of this Reserva.
        :rtype: int
        """
        return self._numero_aula

    @numero_aula.setter
    def numero_aula(self, numero_aula: int):
        """
        Sets the numero_aula of this Reserva.

        :param numero_aula: The numero_aula of this Reserva.
        :type numero_aula: int
        """

        self._numero_aula = numero_aula

    @property
    def horas(self) -> int:
        """
        Gets the horas of this Reserva.

        :return: The horas of this Reserva.
        :rtype: int
        """
        return self._horas

    @horas.setter
    def horas(self, horas: int):
        """
        Sets the horas of this Reserva.

        :param horas: The horas of this Reserva.
        :type horas: int
        """

        self._horas = horas

