swagger: '2.0'
info:
  version: 1.0.0
  title: API para la gestión de cobros y pagos
  description: API para la gestión de las matrículas y las nóminas
host: 'localhost:8080'
basePath: /cobros
tags:
  - name: Pagos
  - name: Matricula
  - name: Alumno
  - name: Profesor
schemes:
  - https
paths:
  /alumno:
    post:
      tags:
        - Alumno
      summary: Crea un alumno
      description: Añade un alumno a la lista de alumnos
      parameters:
        - name: dni
          in: body
          description: El alumno ha sido creado
          schema:
            required:
              - dni
            properties:
              dni:
                type: integer
              Nombre:
                type: string
              Apellidos:
                type: string
              Asignatura:
                type: string
              Plazos:
                type: integer
      responses:
        '200':
          description: Alumno creado correctamente
        '400':
          description: El alumno no se ha podido crear
  /profesor:
    post:
      tags:
        - Profesor
      summary: Crea un profesor
      description: Añade un profesor a la lista de profesores
      parameters:
        - name: dni
          in: body
          description: El profesor ha sido creado
          schema:
            required:
              - dni
            properties:
              dni:
                type: integer
              Nombre:
                type: string
              Apellidos:
                type: string
      responses:
        '200':
          description: Profesor creado correctamente
        '400':
          description: Profesor no creado correctamente
  /pagos:
    get:
      tags:
        - Pagos
      summary: Consulta la nomina del profesor
      description: hace una consulta para comprobar la nomina del profesor
      parameters:
        - name: dni
          in: query
          description: DNI del profesor
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              required:
                - dni
              properties:
                dni:
                  type: integer
        '400':
          description: El profesor no existe
  /matricula:
    post:
      tags:
        - Matricula
      summary: Crea matricula
      description: Crea matricula
      parameters:
        - name: dni
          in: body
          description: La matricula ha sido creada
          schema:
            required:
              - dni
            properties:
              dni:
                type: integer
              id:
                type: integer
              precio:
                type: integer
              plazos:
                type: integer
              reserva:
                type: integer
      responses:
        '200':
          description: OK
        '400':
          description: No se ha creado correctamente
